### ISSUE TITLE
Make the iframe's min-height always 100vh

### ISSUE THREAD

**Issue by MarcCote** [nodeGame/nodegame-window#8]
Is there a way to set the iframe's min-height to "100vh" and prevent nodegame from overwriting it?
https://github.com/nodeGame/nodegame-window/blob/master/lib/GameWindow.js#L1971
`iframe.style['min-height'] = '100vh';`

**Comment by shakty** [comment]
At the moment no, but I can an option to disable automatic adjustment of the frame height. 
This might cause some unpredictable behavior, but if you want to disable it, I assume you know what you are doing.

Just to be clear, you want to set the iframe min-height once at the beginning, and you want nodeGame not to tinker with that ever again during the experiment?

**Comment by MarcCote** [comment]
Yeah, the thing is that "100vh" will adapt automatically. At least it appears so on Chrome and FF.

**Comment by shakty** [comment]
This solution does not appear to be working for me. With min-height equal to 100vh the iframe is cut, and there is no more scrollbar to see what's left outside of the viewport.

**Comment by shakty** [comment]
You can enable and disable adjusting the frame height with the command
```
W.init(adjustFrameHeight: false/true);
```
By default is TRUE, so you might want to disable after Parchment loads, and re-enable it for the exit survey.

To try it, just pull window and then start the server with node launcher -b window

Let me know if this is the expected behavior

**Comment by MarcCote** [comment]
That works like a charm. Thanks.
